# Install pre-commit hooks via
# pre-commit install

ci:
  autofix_prs: false
  autofix_commit_msg: |
    '[pre-commit.ci 🤖] Apply code format tools to PR'
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # frozen: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: bc7af46104f0f5368b95878decf720f9f00c2559 # frozen: v3.4.2
    hooks:
      - id: prettier
        files: \.(css|html|md|yml|yaml|toml)
        args: [--prose-wrap=preserve]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: f0b5944bef86f50d875305821a0ab0d8c601e465 # frozen: v0.8.4
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes", "--exit-non-zero-on-fix"]
      - id: ruff-format

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 78a9dcbecf4f755f65d1f3dec556bc249d723600 # frozen: 1.19.1
    hooks:
      - id: blacken-docs

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 648203cec3e499b9eff54a24d6cf4b25ce02eb1e # frozen: v1.14.0
    hooks:
      - id: mypy
        exclude: |
          (?x)(
            ^example_pkg_src/
          )

  - repo: https://github.com/codespell-project/codespell
    rev: "193cd7d27cd571f79358af09a8fb8997e54f8fff" # frozen: v2.3.0
    hooks:
      - id: codespell
        args: ["-L", "ans"]

  - repo: https://github.com/jsh9/markdown-toc-creator
    rev: "b7b53d559b569730c4ebca86e9ab1a9d796a2214" # frozen: v0.0.8
    hooks:
      - id: markdown-toc-creator
        files: README.md
        args: ["--skip-first-n-lines=4"]
