[project]
name = "spin"
version = "0.2rc0.dev0"
requires-python = ">=3.7"
description = "Developer tool for scientific Python libraries"
license = {file = "LICENSE"}
maintainers = [
  {name = "Scientific Python", email = "spin@discuss.scientific-python.org"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]
dependencies = [
  "click",
  "toml",
  "colorama; platform_system == 'Windows'"
]

[project.optional-dependencies]
lint = ["pre-commit >= 3.1"]

[project.urls]
homepage = "https://github.com/scientific-python/spin"

[tool.setuptools.packages.find]
include = ["spin*"]

[tool.pytest.ini_options]
filterwarnings = [
  "ignore:cannot collect 'test' because it is not a function:",
]
