[project]
name = "devpy"
version = "0.1a3.dev0"
requires-python = ">=3.7"
description = "Developer tool for scientific Python libraries"
license = {file = "LICENSE"}
maintainers = [
  {name = "Scientific Python", email = "devpy@discuss.scientific-python.org"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]
dependencies = [
  "click",
  "toml"
]

[project.optional-dependencies]
lint = ["pre-commit >= 2.20"]

[project.urls]
homepage = "https://github.com/scientific-python/devpy"

[tool.setuptools.packages.find]
include = ["devpy*"]

[tool.pytest.ini_options]
filterwarnings = [
  "ignore:cannot collect 'test' because it is not a function:",
]

[tool.devpy]
package = 'devpy'

[tool.devpy.commands]
# If you don't need sections, you can also provide a list of commands under [tool.devpy]:
#
# commands = ["devpy.build", "devpy.test", "devpy.shell", "devpy.ipython", "devpy.python", "custom/cmds.py:example"]

"Build" = ["devpy.build", "devpy.test"]
"Environments" = ["devpy.shell", "devpy.ipython", "devpy.python"]
"Extensions" = ["custom/cmds.py:example"]
